import type { Platform } from "./platforms";

export type Game = { id: string; gameId: string; title: string; slug: string; image: string; platform: Platform; genre: "Open world" | "RPG" | "Indie" | "Racing" | "Action" | "Adventure" | "Co-op" | "Fighting" | "Puzzle" | "Simulation" | "Strategy"; price: number | null; releaseDate?: string; status?: "Coming soon"; searchAliases?: string[]; currency: "EUR"; description: string; };
// Illustrative products only. Prices are not supplier quotes or live offers.
const pcGames: Game[] = [
  { id: "1091500", gameId: "1091500", title: "Cyberpunk 2077", slug: "cyberpunk-2077", image: "/games/cyberpunk-2077.jpg", platform: "PC", genre: "Open world", price: 29.99, currency: "EUR", description: "Step into Night City as V, a mercenary navigating a sprawling world of cybernetic upgrades, dangerous deals and choices that shape your story." },
  { id: "1245620", gameId: "1245620", title: "ELDEN RING", slug: "elden-ring", image: "/games/elden-ring.jpg", platform: "PC", genre: "RPG", price: 39.99, currency: "EUR", description: "Explore the Lands Between, uncover its mysteries and take on formidable enemies in a vast fantasy action RPG." },
  { id: "1086940", gameId: "1086940", title: "Baldur's Gate 3", slug: "baldurs-gate-3", image: "/games/baldurs-gate-3.jpg", platform: "PC", genre: "RPG", price: 49.99, currency: "EUR", description: "Gather your party for a story-rich adventure where your choices, companions and a roll of the dice can change everything." },
  { id: "1551360", gameId: "1551360", title: "Forza Horizon 5", slug: "forza-horizon-5", image: "/games/forza-horizon-5.jpg", platform: "PC", genre: "Racing", price: 34.99, currency: "EUR", description: "Head out on an open-world driving adventure through Mexico, from sun-soaked roads to jungles, deserts and bustling cities." },
  { id: "1145360", gameId: "1145360", title: "Hades", slug: "hades", image: "/games/hades.jpg", platform: "PC", genre: "Indie", price: 14.99, currency: "EUR", description: "Defy the god of the dead and battle your way out of the Underworld in an action-packed roguelike. Every escape attempt brings a new story." },
  { id: "367520", gameId: "367520", title: "Hollow Knight", slug: "hollow-knight", image: "/games/hollow-knight.jpg", platform: "PC", genre: "Indie", price: 9.99, currency: "EUR", description: "Descend into a beautifully drawn underground kingdom. Discover forgotten paths, face challenging foes and unravel the secrets of Hallownest." },
  { id: "990080", gameId: "990080", title: "Hogwarts Legacy", slug: "hogwarts-legacy", image: "/games/hogwarts-legacy.jpg", platform: "PC", genre: "Open world", price: 29.99, currency: "EUR", description: "Make Hogwarts your home, master spells and venture beyond the castle in a wizarding adventure set in the nineteenth century." },
  { id: "292030", gameId: "292030", title: "The Witcher 3: Wild Hunt", slug: "the-witcher-3", image: "/games/the-witcher-3.jpg", platform: "PC", genre: "Open world", price: 19.99, currency: "EUR", description: "Follow Geralt of Rivia across a war-torn continent, tracking monsters and making difficult choices in search of someone he considers family." },
  { id: "275850", gameId: "275850", title: "No Man's Sky", slug: "no-mans-sky", image: "/games/no-mans-sky.jpg", platform: "PC", genre: "Open world", price: 24.99, currency: "EUR", description: "Chart your own route through a vast universe. Discover strange planets, build a base and journey from one star system to the next." },
  { id: "413150", gameId: "413150", title: "Stardew Valley", slug: "stardew-valley", image: "/games/stardew-valley.jpg", platform: "PC", genre: "Simulation", price: 12.99, currency: "EUR", description: "Turn an overgrown plot into a thriving farm, get to know your neighbours and find your own rhythm in the countryside." },
  { id: "588650", gameId: "588650", title: "Dead Cells", slug: "dead-cells", image: "/games/dead-cells.jpg", platform: "PC", genre: "Indie", price: 17.99, currency: "EUR", description: "Fight through an ever-changing castle with an expanding arsenal of weapons. Learn from every defeat and return for another run." },
  { id: "504230", gameId: "504230", title: "Celeste", slug: "celeste", image: "/games/celeste.jpg", platform: "PC", genre: "Indie", price: 9.99, currency: "EUR", description: "Help Madeline climb Celeste Mountain through precise platforming challenges and a personal story about finding the strength to keep going." },
  { id: "2379780", gameId: "2379780", title: "Balatro", slug: "balatro", image: "/games/balatro.jpg", platform: "PC", genre: "Strategy", price: 12.99, currency: "EUR", description: "Build surprising combinations of poker hands and powerful Jokers in a roguelike card game where every round can change your strategy." },
  { id: "268910", gameId: "268910", title: "Cuphead", slug: "cuphead", image: "/games/cuphead.jpg", platform: "PC", genre: "Indie", price: 14.99, currency: "EUR", description: "Take on imaginative bosses in a hand-drawn world inspired by classic cartoons. Play solo or bring a friend for the challenge." },
  { id: "1057090", gameId: "1057090", title: "Ori and the Will of the Wisps", slug: "ori-and-the-will-of-the-wisps", image: "/games/ori-and-the-will-of-the-wisps.jpg", platform: "PC", genre: "Adventure", price: 14.99, currency: "EUR", description: "Guide a small spirit through a luminous forest, discover new abilities and follow a moving adventure about friendship and sacrifice." },
  { id: "1426210", gameId: "1426210", title: "It Takes Two", slug: "it-takes-two", image: "/games/it-takes-two.jpg", platform: "PC", genre: "Co-op", price: 24.99, currency: "EUR", description: "Team up with another player as Cody and May in a cooperative adventure filled with inventive puzzles, playful worlds and unexpected transformations." },
  { id: "1244090", gameId: "1244090", title: "Sea of Stars", slug: "sea-of-stars", image: "/games/sea-of-stars.jpg", platform: "PC", genre: "RPG", price: 24.99, currency: "EUR", description: "Travel with two Children of the Solstice through a colourful fantasy world, combining timed attacks and turn-based battles with a grand adventure." },
  { id: "1868140", gameId: "1868140", title: "DAVE THE DIVER", slug: "dave-the-diver", image: "/games/dave-the-diver.jpg", platform: "PC", genre: "Adventure", price: 14.99, currency: "EUR", description: "Explore the mysterious Blue Hole by day and run a sushi restaurant by night, meeting an eccentric cast along the way." },
  { id: "2215430", gameId: "2215430", title: "Ghost of Tsushima Director's Cut", slug: "ghost-of-tsushima", image: "/games/ghost-of-tsushima.jpg", platform: "PC", genre: "Open world", price: 39.99, currency: "EUR", description: "Become Jin Sakai and defend Tsushima, balancing samurai tradition with new tactics across wind-swept fields, forests and mountains." },
  { id: "2322010", gameId: "2322010", title: "God of War Ragnarök", slug: "god-of-war-ragnarok", image: "/games/god-of-war-ragnarok.jpg", platform: "PC", genre: "Action", price: 39.99, currency: "EUR", description: "Join Kratos and Atreus on a journey through the Nine Realms as they face difficult choices and the approach of Ragnarök." },
  { id: "2420110", gameId: "2420110", title: "Horizon Forbidden West Complete Edition", slug: "horizon-forbidden-west", image: "/games/horizon-forbidden-west.jpg", platform: "PC", genre: "Open world", price: 34.99, currency: "EUR", description: "Travel west with Aloy into a beautiful but dangerous frontier, uncovering ancient secrets and confronting extraordinary machines." },
  { id: "1817070", gameId: "1817070", title: "Marvel's Spider-Man Remastered", slug: "marvels-spider-man-remastered", image: "/games/marvels-spider-man-remastered.jpg", platform: "PC", genre: "Action", price: 29.99, currency: "EUR", description: "Swing through Marvel's New York as an experienced Peter Parker, balancing his personal life with the responsibility of protecting the city." },
  { id: "2050650", gameId: "2050650", title: "Resident Evil 4", slug: "resident-evil-4", image: "/games/resident-evil-4.jpg", platform: "PC", genre: "Action", price: 29.99, currency: "EUR", description: "Follow Leon S. Kennedy into a remote village on a rescue mission that becomes a tense struggle against a terrifying new threat." },
  { id: "1627720", gameId: "1627720", title: "Lies of P", slug: "lies-of-p", image: "/games/lies-of-p.jpg", platform: "PC", genre: "RPG", price: 34.99, currency: "EUR", description: "Explore the fallen city of Krat as a puppet searching for answers, mastering demanding combat and deciding when to tell the truth." },
  { id: "1778820", gameId: "1778820", title: "TEKKEN 8", slug: "tekken-8", image: "/games/tekken-8.jpg", platform: "PC", genre: "Fighting", price: 39.99, currency: "EUR", description: "Enter the next chapter of the Mishima saga with a varied roster, explosive battles and a combat system built around taking the initiative." },
  { id: "1364780", gameId: "1364780", title: "Street Fighter 6", slug: "street-fighter-6", image: "/games/street-fighter-6.jpg", platform: "PC", genre: "Fighting", price: 29.99, currency: "EUR", description: "Learn your favourite fighter, explore World Tour and challenge rivals in a colourful new chapter of Capcom's fighting series." },
  { id: "782330", gameId: "782330", title: "DOOM Eternal", slug: "doom-eternal", image: "/games/doom-eternal.jpg", platform: "PC", genre: "Action", price: 19.99, currency: "EUR", description: "Become the Doom Slayer and battle the armies of Hell with fast movement, heavy weapons and a relentless rhythm of combat." },
  { id: "1446780", gameId: "1446780", title: "Monster Hunter Rise", slug: "monster-hunter-rise", image: "/games/monster-hunter-rise.jpg", platform: "PC", genre: "RPG", price: 19.99, currency: "EUR", description: "Master a weapon, learn the habits of formidable monsters and protect Kamura Village with nimble Wirebug movement and a trusty Palamute." },
  { id: "620", gameId: "620", title: "Portal 2", slug: "portal-2", image: "/games/portal-2.jpg", platform: "PC", genre: "Puzzle", price: 7.99, currency: "EUR", description: "Think your way through Aperture Science using a portal gun, inventive test chambers and the unmistakable wit of GLaDOS." },
  { id: "646570", gameId: "646570", title: "Slay the Spire", slug: "slay-the-spire", image: "/games/slay-the-spire.jpg", platform: "PC", genre: "Strategy", price: 12.99, currency: "EUR", description: "Craft a deck, discover powerful relics and make your way up a changing tower where every card and route can shape your run." },
  { id: "632470", gameId: "632470", title: "Disco Elysium - The Final Cut", slug: "disco-elysium", image: "/games/disco-elysium.jpg", platform: "PC", genre: "RPG", price: 19.99, currency: "EUR", description: "Solve a murder as a detective with a fractured memory, an unusual inner dialogue and countless ways to approach the city around you." },
  { id: "553420", gameId: "553420", title: "TUNIC", slug: "tunic", image: "/games/tunic.jpg", platform: "PC", genre: "Indie", price: 19.99, currency: "EUR", description: "Explore a mysterious land as a small fox, uncovering hidden paths and piecing together a beautiful manual that holds the world's secrets." },
  { id: "1562430", gameId: "1562430", title: "DREDGE", slug: "dredge", image: "/games/dredge.jpg", platform: "PC", genre: "Adventure", price: 17.99, currency: "EUR", description: "Captain a fishing boat through a remote archipelago, sell your catch and discover what lurks beneath the surface after sunset." },
  { id: "1332010", gameId: "1332010", title: "Stray", slug: "stray", image: "/games/stray.jpg", platform: "PC", genre: "Adventure", price: 19.99, currency: "EUR", description: "See a forgotten cybercity through the eyes of a stray cat, finding a way home with the help of a small flying companion." },
  { id: "870780", gameId: "870780", title: "Control Ultimate Edition", slug: "control-ultimate-edition", image: "/games/control-ultimate-edition.jpg", platform: "PC", genre: "Action", price: 19.99, currency: "EUR", description: "Enter the shifting halls of the Federal Bureau of Control as Jesse Faden and use supernatural abilities to confront a mysterious invasion." },
  { id: "1649240", gameId: "1649240", title: "Returnal", slug: "returnal", image: "/games/returnal.jpg", platform: "PC", genre: "Action", price: 34.99, currency: "EUR", description: "Break a cycle of survival on an alien planet, combining fast combat with an unfolding mystery that changes with every return." },
  { id: "814380", gameId: "814380", title: "Sekiro: Shadows Die Twice", slug: "sekiro-shadows-die-twice", image: "/games/sekiro-shadows-die-twice.jpg", platform: "PC", genre: "Action", price: 29.99, currency: "EUR", description: "Follow a shinobi's quest in a reimagined sixteenth-century Japan, mastering precise swordplay, stealth and the tools of a prosthetic arm." },
  { id: "1196590", gameId: "1196590", title: "Resident Evil Village", slug: "resident-evil-village", image: "/games/resident-evil-village.jpg", platform: "PC", genre: "Action", price: 24.99, currency: "EUR", description: "Return as Ethan Winters and search for your daughter in a secluded village filled with unforgettable characters and unsettling dangers." },
];

// Console entries demonstrate separate product editions, not confirmed stock.
// Nintendo examples are for Nintendo Switch; Xbox examples are Series X|S.
const demoEditions: Record<string, Platform[]> = {
  "cyberpunk-2077": ["PS5", "Xbox"],
  "elden-ring": ["PS5", "Xbox"],
  "baldurs-gate-3": ["PS5", "Xbox"],
  "forza-horizon-5": ["PS5", "Xbox"],
  "hades": ["PS5", "Xbox", "Nintendo"],
  "hollow-knight": ["Nintendo"],
  "hogwarts-legacy": ["PS5", "Xbox", "Nintendo"],
  "the-witcher-3": ["PS5", "Xbox", "Nintendo"],
  "no-mans-sky": ["PS5", "Xbox", "Nintendo"],
  "stardew-valley": ["Xbox", "Nintendo"],
  "dead-cells": ["PS5", "Xbox", "Nintendo"],
  "celeste": ["Xbox", "Nintendo"],
  "balatro": ["PS5", "Xbox", "Nintendo"],
  "cuphead": ["Xbox", "Nintendo"],
  "ori-and-the-will-of-the-wisps": ["Xbox", "Nintendo"],
  "it-takes-two": ["PS5", "Xbox", "Nintendo"],
  "sea-of-stars": ["PS5", "Xbox", "Nintendo"],
  "dave-the-diver": ["PS5", "Nintendo"],
  "ghost-of-tsushima": ["PS5"],
  "god-of-war-ragnarok": ["PS5"],
  "horizon-forbidden-west": ["PS5"],
  "marvels-spider-man-remastered": ["PS5"],
  "resident-evil-4": ["PS5", "Xbox"],
  "lies-of-p": ["PS5", "Xbox"],
  "tekken-8": ["PS5", "Xbox"],
  "street-fighter-6": ["PS5", "Xbox"],
  "doom-eternal": ["PS5", "Xbox", "Nintendo"],
  "monster-hunter-rise": ["PS5", "Xbox", "Nintendo"],
  "portal-2": [],
  "slay-the-spire": ["Xbox", "Nintendo"],
  "disco-elysium": ["PS5", "Xbox", "Nintendo"],
  "tunic": ["PS5", "Xbox", "Nintendo"],
  "dredge": ["PS5", "Xbox", "Nintendo"],
  "stray": ["PS5", "Xbox", "Nintendo"],
  "control-ultimate-edition": ["PS5", "Xbox"],
  "returnal": ["PS5"],
  "sekiro-shadows-die-twice": [],
  "resident-evil-village": ["PS5", "Xbox"],
};

const gtaVI: Game = {
  id: "gta-vi-ps5",
  gameId: "gta-vi",
  title: "Grand Theft Auto VI",
  slug: "grand-theft-auto-vi-ps5",
  image: "/games/gta-vi.jpg",
  platform: "PS5",
  genre: "Open world",
  price: null,
  currency: "EUR",
  status: "Coming soon",
  releaseDate: "November 19, 2026",
  searchAliases: ["GTA 6", "GTA VI", "Grand Theft Auto 6"],
  description: "Return to Vice City with Jason and Lucia in Rockstar Games' next open-world adventure, set across the state of Leonida.",
};

const spotlightGames: Game[] = [
  gtaVI,
  { ...gtaVI, id: "gta-vi-xbox", slug: "grand-theft-auto-vi-xbox", platform: "Xbox" },
  {
    id: "marvels-wolverine-ps5",
    gameId: "marvels-wolverine",
    title: "Marvel's Wolverine",
    slug: "marvels-wolverine-ps5",
    image: "/games/marvels-wolverine.jpg",
    platform: "PS5",
    genre: "Action",
    price: 59.99,
    currency: "EUR",
    description: "Take on an original, story-driven adventure as Logan, with fierce claw combat and a journey through Canada, Japan and Madripoor. Developed by Insomniac Games for PlayStation 5.",
  },
];

export const mockGames: Game[] = [
  ...spotlightGames,
  ...pcGames,
  ...pcGames.flatMap((game) =>
    demoEditions[game.slug].map((platform) => ({
      ...game,
      id: `${game.id}-${platform.toLowerCase()}`,
      slug: `${game.slug}-${platform.toLowerCase()}`,
      platform,
    })),
  ),
];
